version: '3.9'

services:
  frontend:
    image: ghcr.io/marchitecht/frontend:latest
    restart: always

  # backend:
  #   image: ghcr.io/your-org/backend:latest
  #   restart: always
  #   environment:
  #     - DATABASE_URL=postgres://user:pass@db:5432/app

  nginx:
    image: nginx:stable
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      # - backend
    ports:
      - "80:80"