name: Build & Deploy FrontEnd

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout РЕПОЗИТОРИЯ FRONTEND
      - name: Checkout frontend repo
        uses: actions/checkout@v3
        with:
          repository: marchitecht/frontend
          token: ${{ secrets.GITHUB_TOKEN }}
          path: frontend

      # 2. Логин в GHCR
      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 3. Сборка Docker-образа из frontend/
      - name: Build Docker image
        run: |
          docker build \
            -t ghcr.io/marchitecht/frontend:latest \
            frontend

      # 4. Push образа
      - name: Push Docker image
        run: |
          docker push ghcr.io/marchitecht/frontend:latest

      # 5. Деплой на сервер
      - name: Deploy to server
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22
          script: |
            cd /root/devstack
            docker-compose pull frontend
            docker-compose up -d frontend
